# ===========  Master Boot Image Configuration for KW45xx  ===========
# ----------------------------------------------------------------------------------------------------
#                                         == Basic Settings ==                                        
# ----------------------------------------------------------------------------------------------------
family: kw45b41z8  # [Required], MCU family name
outputImageExecutionTarget: xip  # [Required], Application target; Definition if application is Execute in Place(XiP) or loaded to RAM during reset sequence; Possible options: ['xip', 'load-to-ram']
outputImageAuthenticationType: Signed  # [Required], Type of boot image authentication; Specification of final master boot image authentication; Possible options:['plain', 'crc', 'signed', 'signed-encrypted', 'signed-nxp']
masterBootOutputFile: ../workspace/bootable_images/OEM_Return_Signed.xip  # [Required], Master Boot Image name; The file for Master Boot Image result file.
inputImageFile: ../OEM_Return_Plain.bin  # [Required], Plain application image; The input application image to by modified to Master Boot Image.
outputImageExecutionAddress: 0x00000000  # [Required], Loading address of application; Application loading address in RAM if not XiP, otherwise address of load in XiP.
firmwareVersion: 0x0  # [Optional], Firmware version; Version of application image firmware.
outputImageSubtype: main # [Optional], Image subtype determine the image use in MCU (Main application or something else).
# ======================================================================================================================
#                                              == Certificate Block V2.1 ==
# ======================================================================================================================
# -----------------------------===== Certificate Block binary/config file [Required] =====------------------------------
# Description: Path to certificate block binary or config file.
certBlock: ../workspace/keys/ROT1_cert_block.bin
# ======================================================================================================================
#                                              == Image Signing Settings ==
# ======================================================================================================================
# -------------------------------===== Signature Provider [Conditionally required] =====--------------------------------
# Description: Signature provider configuration in format 'type=<sp_type>;<key1>=<value1>;<key2>=<value2>".
signProvider: type=file;file_path=../workspace/keys/ROT1_p384.pem

# ----------------------------------------------------------------------------------------------------
#                                      == Trust Zone Settings ==                                      
# ----------------------------------------------------------------------------------------------------
enableTrustZone: true  # [Optional], TrustZone enable option, If not specified, the Trust zone is disabled.
